source 'https://github.com/CocoaPods/Specs.git'

platform :ios,  '10.0'
use_frameworks!
inhibit_all_warnings!

target 'NSSetUTF8Log_Example' do
  pod 'NSSetUTF8Log', :path => '../'

  target 'NSSetUTF8Log_Tests' do
    inherit! :search_paths

    
  end
end
